# Generated by Django 5.2.4 on 2026-05-28 14:56

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'კატეგორია',
                'verbose_name_plural': 'კატეგორიები',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='სათაური')),
                ('slug', models.SlugField(max_length=300, unique=True, verbose_name='Slug')),
                ('excerpt', models.TextField(max_length=500, verbose_name='მოკლე შინაარსი')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='სტატიის ტექსტი')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='მთავარი სურათი')),
                ('is_published', models.BooleanField(default=False, verbose_name='გამოქვეყნებული')),
                ('is_featured', models.BooleanField(default=False, verbose_name='გამოსახული')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='გამოქვეყნების თარიღი')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='ავტორი')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory', verbose_name='კატეგორია')),
            ],
            options={
                'verbose_name': 'სტატია',
                'verbose_name_plural': 'სტატიები',
                'ordering': ['-published_at'],
            },
        ),
    ]
