# Generated by Django 5.2.4 on 2026-06-03 14:37

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcategory',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='სახელი (EN)'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='სახელი (RU)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='სტატიის ტექსტი (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='body_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='სტატიის ტექსტი (RU)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='მოკლე შინაარსი (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='excerpt_ru',
            field=models.TextField(blank=True, max_length=500, verbose_name='მოკლე შინაარსი (RU)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='სათაური (EN)'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='სათაური (RU)'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='სახელი (ქა)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='სტატიის ტექსტი (ქა)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(max_length=500, verbose_name='მოკლე შინაარსი (ქა)'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=300, verbose_name='სათაური (ქა)'),
        ),
    ]
