# Generated by Django 5.2.4 on 2026-05-28 14:56

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='სათაური')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='Stethoscope', help_text='lucide-react ხატულის სახელი, მაგ: Brain, Shield, Activity', max_length=50, verbose_name='ხატულა (lucide icon name)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='სურათი')),
                ('short_description', models.CharField(max_length=300, verbose_name='მოკლე აღწერა')),
                ('full_description', ckeditor.fields.RichTextField(blank=True, verbose_name='სრული აღწერა')),
                ('duration', models.CharField(blank=True, help_text='მაგ: 30-60 წუთი', max_length=100, verbose_name='ხანგრძლივობა')),
                ('price', models.CharField(blank=True, default='კონსულტაციით', max_length=100, verbose_name='ფასი')),
                ('is_featured', models.BooleanField(default=False, verbose_name='გამოსახული')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'სერვისი',
                'verbose_name_plural': 'სერვისები',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='ტექსტი')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='services.service', verbose_name='სერვისი')),
            ],
            options={
                'verbose_name': 'სერვისის მახასიათებელი',
                'verbose_name_plural': 'სერვისის მახასიათებლები',
            },
        ),
    ]
