# Generated by Django 5.2.4 on 2026-06-03 14:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='full_description_en',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='სრული აღწერა (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='full_description_ru',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='სრული აღწერა (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='მოკლე აღწერა (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='short_description_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='მოკლე აღწერა (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='სათაური (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='სათაური (RU)'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='text_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='ტექსტი (EN)'),
        ),
        migrations.AddField(
            model_name='servicefeature',
            name='text_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='ტექსტი (RU)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.CharField(blank=True, max_length=100, verbose_name='ხანგრძლივობა'),
        ),
        migrations.AlterField(
            model_name='service',
            name='full_description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='სრული აღწერა (ქა)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(max_length=300, verbose_name='მოკლე აღწერა (ქა)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200, verbose_name='სათაური (ქა)'),
        ),
        migrations.AlterField(
            model_name='servicefeature',
            name='text',
            field=models.CharField(max_length=200, verbose_name='ტექსტი (ქა)'),
        ),
    ]
