# Generated by Django 5.2.4 on 2026-06-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_full_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 ფაილი. თუ ვიდეო ატვირთულია, სურათი არ გამოჩნდება.', null=True, upload_to='services/videos/', verbose_name='ვიდეო'),
        ),
    ]
