# Generated by Django 5.2.4 on 2026-06-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO აღწერა (ქა)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO აღწერა (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description_ru',
            field=models.CharField(blank=True, max_length=160, verbose_name='SEO აღწერა (RU)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO სათაური (ქა)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title_en',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO სათაური (EN)'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title_ru',
            field=models.CharField(blank=True, max_length=70, verbose_name='SEO სათაური (RU)'),
        ),
    ]
