# Generated by Django 5.2.4 on 2026-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=200, verbose_name='პაციენტის სახელი')),
                ('phone', models.CharField(max_length=30, verbose_name='ტელეფონი')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ელ-ფოსტა')),
                ('service', models.CharField(blank=True, max_length=200, verbose_name='სერვისი')),
                ('preferred_date', models.DateTimeField(blank=True, null=True, verbose_name='სასურველი თარიღი')),
                ('notes', models.TextField(blank=True, verbose_name='შენიშვნა')),
                ('status', models.CharField(choices=[('new', 'ახალი'), ('contacted', 'დაკავშირებული'), ('scheduled', 'ჩანიშნული'), ('completed', 'დასრულებული'), ('cancelled', 'გაუქმებული')], default='new', max_length=20, verbose_name='სტატუსი')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='განახლების თარიღი')),
            ],
            options={
                'verbose_name': 'კონსულტაცია',
                'verbose_name_plural': 'კონსულტაციები',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='სახელი')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ელ-ფოსტა')),
                ('phone', models.CharField(max_length=30, verbose_name='ტელეფონი')),
                ('service', models.CharField(blank=True, max_length=200, verbose_name='სერვისი')),
                ('message', models.TextField(blank=True, verbose_name='შეტყობინება')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='გაგზავნის თარიღი')),
                ('is_read', models.BooleanField(default=False, verbose_name='წაკითხული')),
            ],
            options={
                'verbose_name': 'შეტყობინება',
                'verbose_name_plural': 'შეტყობინებები',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ელ-ფოსტა')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='გამოწერის თარიღი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
            ],
            options={
                'verbose_name': 'Newsletter გამომწერი',
                'verbose_name_plural': 'Newsletter გამომწერები',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
