# Generated by Django 5.2.4 on 2026-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='ჩვენ შესახებ', max_length=200, verbose_name='Hero სათაური')),
                ('hero_subtitle', models.CharField(blank=True, max_length=300, verbose_name='Hero ქვესათაური')),
                ('mission', models.TextField(blank=True, verbose_name='მისია')),
                ('vision', models.TextField(blank=True, verbose_name='ვიზია')),
            ],
            options={
                'verbose_name': 'ჩვენ შესახებ გვერდი',
                'verbose_name_plural': 'ჩვენ შესახებ გვერდი',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='სათაური')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('image', models.ImageField(blank=True, null=True, upload_to='certifications/', verbose_name='სერტიფიკატის სურათი')),
                ('issued_by', models.CharField(blank=True, max_length=200, verbose_name='გამცემი ორგანიზაცია')),
                ('issued_year', models.CharField(blank=True, max_length=10, verbose_name='გაცემის წელი')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'სერტიფიკატი',
                'verbose_name_plural': 'სერტიფიკატები',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='წელი')),
                ('title', models.CharField(max_length=200, verbose_name='სათაური')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'ისტორიის ჩანაწერი',
                'verbose_name_plural': 'კომპანიის ისტორია',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='Heart', max_length=50, verbose_name='ხატულა (lucide icon name)')),
                ('title', models.CharField(max_length=100, verbose_name='სათაური')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'ღირებულება',
                'verbose_name_plural': 'ღირებულებები',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='სახელი')),
                ('role', models.CharField(max_length=200, verbose_name='პოზიცია')),
                ('bio', models.TextField(blank=True, verbose_name='ბიოგრაფია')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/', verbose_name='ფოტო')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'გუნდის წევრი',
                'verbose_name_plural': 'გუნდი',
                'ordering': ['order'],
            },
        ),
    ]
