# Generated by Django 5.2.4 on 2026-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='Hero ქვესათაური (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='Hero ქვესათაური (RU)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hero სათაური (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='Hero სათაური (RU)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_en',
            field=models.TextField(blank=True, verbose_name='მისია (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='mission_ru',
            field=models.TextField(blank=True, verbose_name='მისია (RU)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_en',
            field=models.TextField(blank=True, verbose_name='ვიზია (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='vision_ru',
            field=models.TextField(blank=True, verbose_name='ვიზია (RU)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='აღწერა (EN)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='აღწერა (RU)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='სათაური (EN)'),
        ),
        migrations.AddField(
            model_name='certification',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='სათაური (RU)'),
        ),
        migrations.AddField(
            model_name='companytimeline',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='აღწერა (EN)'),
        ),
        migrations.AddField(
            model_name='companytimeline',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='აღწერა (RU)'),
        ),
        migrations.AddField(
            model_name='companytimeline',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='სათაური (EN)'),
        ),
        migrations.AddField(
            model_name='companytimeline',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='სათაური (RU)'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='აღწერა (EN)'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='აღწერა (RU)'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='სათაური (EN)'),
        ),
        migrations.AddField(
            model_name='companyvalue',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='სათაური (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_en',
            field=models.TextField(blank=True, verbose_name='ბიოგრაფია (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='bio_ru',
            field=models.TextField(blank=True, verbose_name='ბიოგრაფია (RU)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='პოზიცია (EN)'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='role_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='პოზიცია (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=300, verbose_name='Hero ქვესათაური (ქა)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default='ჩვენ შესახებ', max_length=200, verbose_name='Hero სათაური (ქა)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='mission',
            field=models.TextField(blank=True, verbose_name='მისია (ქა)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='vision',
            field=models.TextField(blank=True, verbose_name='ვიზია (ქა)'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(blank=True, verbose_name='აღწერა (ქა)'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=200, verbose_name='სათაური (ქა)'),
        ),
        migrations.AlterField(
            model_name='companytimeline',
            name='description',
            field=models.TextField(blank=True, verbose_name='აღწერა (ქა)'),
        ),
        migrations.AlterField(
            model_name='companytimeline',
            name='title',
            field=models.CharField(max_length=200, verbose_name='სათაური (ქა)'),
        ),
        migrations.AlterField(
            model_name='companyvalue',
            name='description',
            field=models.TextField(verbose_name='აღწერა (ქა)'),
        ),
        migrations.AlterField(
            model_name='companyvalue',
            name='title',
            field=models.CharField(max_length=100, verbose_name='სათაური (ქა)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='bio',
            field=models.TextField(blank=True, verbose_name='ბიოგრაფია (ქა)'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='role',
            field=models.CharField(max_length=200, verbose_name='პოზიცია (ქა)'),
        ),
    ]
