# Generated by Django 5.2.4 on 2026-06-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_hero_subtitle_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutpage',
            options={'verbose_name': 'გვერდის კონტენტი', 'verbose_name_plural': 'გვერდის კონტენტი'},
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='სურათი'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 ფაილი. თუ ვიდეო ატვირთულია, სურათი არ გამოჩნდება.', null=True, upload_to='about/videos/', verbose_name='ვიდეო'),
        ),
    ]
