# Generated by Django 5.2.4 on 2026-06-08 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutpage_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_highlight',
            field=models.CharField(default='შესახებ', max_length=200, verbose_name='სათაური — ოქროსფერი (ქა)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_highlight_en',
            field=models.CharField(blank=True, default='Us', max_length=200, verbose_name='სათაური — ოქროსფერი (EN)'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_highlight_ru',
            field=models.CharField(blank=True, default='нас', max_length=200, verbose_name='სათაური — ოქროსფერი (RU)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(default='ჩვენს', max_length=200, verbose_name='სათაური — თეთრი (ქა)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_en',
            field=models.CharField(blank=True, default='About', max_length=200, verbose_name='სათაური — თეთრი (EN)'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='hero_title_ru',
            field=models.CharField(blank=True, default='О', max_length=200, verbose_name='სათაური — თეთრი (RU)'),
        ),
    ]
