# Generated by Django 5.2.4 on 2026-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ახალი შენ', max_length=100, verbose_name='საიტის სახელი')),
                ('tagline', models.CharField(default='ახალი შენ – ახალი ცხოვრება', max_length=200, verbose_name='სლოგანი')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='ლოგო')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='Favicon')),
                ('announcement_text', models.CharField(blank=True, help_text='ცარიელი = banner არ გამოჩნდება', max_length=300, verbose_name='განცხადება (header banner)')),
                ('primary_phone', models.CharField(default='+995 555 123 456', max_length=30, verbose_name='მთავარი ტელეფონი')),
                ('secondary_phone', models.CharField(blank=True, max_length=30, verbose_name='დამატებითი ტელეფონი')),
                ('emergency_phone', models.CharField(default='+995 322 911 911', max_length=30, verbose_name='გადაუდებელი ხაზი')),
                ('email', models.EmailField(default='info@akhalishen.ge', max_length=254, verbose_name='ელ-ფოსტა')),
                ('support_email', models.EmailField(blank=True, max_length=254, verbose_name='მხარდაჭერის ელ-ფოსტა')),
                ('address_line1', models.CharField(default='რუსთაველის გამზ. 24', max_length=200, verbose_name='მისამართი 1')),
                ('address_line2', models.CharField(blank=True, default='თბილისი, საქართველო', max_length=200, verbose_name='მისამართი 2')),
                ('google_maps_embed', models.TextField(blank=True, verbose_name='Google Maps embed URL')),
                ('working_hours_weekdays', models.CharField(default='09:00 - 19:00', max_length=100, verbose_name='სამუშაო საათები (ორ-პარ)')),
                ('working_hours_saturday', models.CharField(default='10:00 - 15:00', max_length=100, verbose_name='სამუშაო საათები (შაბ)')),
                ('working_hours_sunday', models.CharField(blank=True, default='დახურულია', max_length=100, verbose_name='სამუშაო საათები (კვი)')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'საიტის პარამეტრები',
                'verbose_name_plural': 'საიტის პარამეტრები',
            },
        ),
    ]
