# Generated by Django 5.2.4 on 2026-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='განცხადება (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='announcement_text_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='განცხადება (RU)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='სლოგანი (EN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='tagline_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='სლოგანი (RU)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='announcement_text',
            field=models.CharField(blank=True, help_text='ცარიელი = banner არ გამოჩნდება', max_length=300, verbose_name='განცხადება (KA) (header banner)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(default='ახალი შენ – ახალი ცხოვრება', max_length=200, verbose_name='სლოგანი (KA)'),
        ),
    ]
