# Generated by Django 5.2.4 on 2026-06-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_announcement_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageSEO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=70, verbose_name='SEO სათაური (ქა)')),
                ('meta_title_en', models.CharField(blank=True, max_length=70, verbose_name='SEO სათაური (EN)')),
                ('meta_title_ru', models.CharField(blank=True, max_length=70, verbose_name='SEO სათაური (RU)')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='SEO აღწერა (ქა)')),
                ('meta_description_en', models.CharField(blank=True, max_length=160, verbose_name='SEO აღწერა (EN)')),
                ('meta_description_ru', models.CharField(blank=True, max_length=160, verbose_name='SEO აღწერა (RU)')),
                ('page_key', models.CharField(choices=[('contact', 'კონტაქტი'), ('products', 'პროდუქტები'), ('services', 'სერვისები'), ('blog', 'ბლოგი'), ('faq', 'FAQ'), ('certifications', 'სერტიფიკაცია'), ('safety', 'უსაფრთხოება'), ('production', 'წარმოება')], max_length=50, unique=True, verbose_name='გვერდი')),
            ],
            options={
                'verbose_name': 'გვერდის SEO',
                'verbose_name_plural': 'გვერდების SEO',
                'ordering': ['page_key'],
            },
        ),
    ]
