# Generated by Django 5.2.4 on 2026-05-28 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, verbose_name='წელი')),
                ('title', models.CharField(max_length=200, verbose_name='სათაური')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'მიღწევა',
                'verbose_name_plural': 'მიღწევები',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='კითხვა')),
                ('answer', models.TextField(verbose_name='პასუხი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='Shield', help_text='lucide-react ხატულის სახელი, მაგ: Shield, Clock, Users', max_length=50, verbose_name='ხატულა (lucide icon name)')),
                ('color', models.CharField(default='from-violet-500/20 to-purple-500/20', max_length=100, verbose_name='ფერის კლასი (Tailwind gradient)')),
                ('title', models.CharField(max_length=100, verbose_name='სათაური')),
                ('description', models.CharField(max_length=300, verbose_name='აღწერა')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'უპირატესობა',
                'verbose_name_plural': 'უპირატესობები',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ახალი შენ –', max_length=200, verbose_name='სათაური')),
                ('title_highlight', models.CharField(default='ახალი ცხოვრება', help_text='ეს ნაწილი გამოჩნდება primary ფერით', max_length=200, verbose_name='გამოკვეთილი ტექსტი')),
                ('description', models.TextField(default='ჩვენი მიზანია დაგეხმაროთ კანინეთობის აღდგენაში და ცხოვრების ხარისხის გაუმჯობესებაში.', verbose_name='აღწერა')),
                ('cta_primary_text', models.CharField(default='დაგვიკავშირდით', max_length=100, verbose_name='ღილაკი 1 ტექსტი')),
                ('cta_primary_link', models.CharField(default='/contact', max_length=200, verbose_name='ღილაკი 1 ბმული')),
                ('cta_secondary_text', models.CharField(default='გაიგე მეტი', max_length=100, verbose_name='ღილაკი 2 ტექსტი')),
                ('cta_secondary_link', models.CharField(default='/about', max_length=200, verbose_name='ღილაკი 2 ბმული')),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='სურათი')),
            ],
            options={
                'verbose_name': 'Hero სექცია',
                'verbose_name_plural': 'Hero სექცია',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='სახელი')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='ლოგო')),
                ('url', models.URLField(blank=True, verbose_name='ვებ-გვერდი')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'პარტნიორი',
                'verbose_name_plural': 'პარტნიორები',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.PositiveIntegerField(verbose_name='ნომერი')),
                ('title', models.CharField(max_length=100, verbose_name='სათაური')),
                ('description', models.TextField(verbose_name='აღწერა')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'პროცესის ნაბიჯი',
                'verbose_name_plural': 'პროცესის ნაბიჯები',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='სათაური')),
                ('journal', models.CharField(max_length=200, verbose_name='ჟურნალი / წყარო')),
                ('date', models.DateField(blank=True, null=True, verbose_name='თარიღი')),
                ('url', models.URLField(blank=True, verbose_name='ბმული')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'პუბლიკაცია',
                'verbose_name_plural': 'პუბლიკაციები',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(help_text='მაგ: 1500+', max_length=50, verbose_name='მნიშვნელობა')),
                ('label', models.CharField(max_length=100, verbose_name='ლეიბლი')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'სტატისტიკა',
                'verbose_name_plural': 'სტატისტიკა',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('role', models.CharField(default='პაციენტი', max_length=100, verbose_name='როლი')),
                ('content', models.TextField(verbose_name='შეფასება')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='ფოტო')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='შეფასება (1-5)')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'მიმოხილვა',
                'verbose_name_plural': 'მიმოხილვები',
                'ordering': ['order'],
            },
        ),
    ]
