# Generated by Django 5.2.4 on 2026-06-03 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(blank=True, verbose_name='პასუხი (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_ru',
            field=models.TextField(blank=True, verbose_name='პასუხი (RU)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='კითხვა (EN)'),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='კითხვა (RU)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_en',
            field=models.CharField(blank=True, max_length=300, verbose_name='აღწერა (EN)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='description_ru',
            field=models.CharField(blank=True, max_length=300, verbose_name='აღწერა (RU)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='სათაური (EN)'),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='სათაური (RU)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_en',
            field=models.TextField(blank=True, verbose_name='აღწერა (EN)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description_ru',
            field=models.TextField(blank=True, verbose_name='აღწერა (RU)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='სათაური (EN)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_highlight_en',
            field=models.CharField(blank=True, max_length=200, verbose_name='გამოკვეთილი ტექსტი (EN)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_highlight_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='გამოკვეთილი ტექსტი (RU)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_ru',
            field=models.CharField(blank=True, max_length=200, verbose_name='სათაური (RU)'),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='ლეიბლი (EN)'),
        ),
        migrations.AddField(
            model_name='stat',
            name='label_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='ლეიბლი (RU)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_en',
            field=models.TextField(blank=True, verbose_name='შეფასება (EN)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='content_ru',
            field=models.TextField(blank=True, verbose_name='შეფასება (RU)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='როლი (EN)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='role_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='როლი (RU)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(verbose_name='პასუხი (ქა)'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(max_length=300, verbose_name='კითხვა (ქა)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.CharField(max_length=300, verbose_name='აღწერა (ქა)'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='title',
            field=models.CharField(max_length=100, verbose_name='სათაური (ქა)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='ჩვენი მიზანია დაგეხმაროთ.', verbose_name='აღწერა (ქა)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title',
            field=models.CharField(default='ახალი შენ –', max_length=200, verbose_name='სათაური (ქა)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='title_highlight',
            field=models.CharField(default='ახალი ცხოვრება', max_length=200, verbose_name='გამოკვეთილი ტექსტი (ქა)'),
        ),
        migrations.AlterField(
            model_name='stat',
            name='label',
            field=models.CharField(max_length=100, verbose_name='ლეიბლი (ქა)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='content',
            field=models.TextField(verbose_name='შეფასება (ქა)'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='role',
            field=models.CharField(default='მომხმარებელი', max_length=100, verbose_name='როლი (ქა)'),
        ),
    ]
