# Generated by Django 5.2.4 on 2026-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_faq_answer_en_faq_answer_ru_faq_question_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='cta_primary_text_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='ღილაკი 1 ტექსტი (EN)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_primary_text_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='ღილაკი 1 ტექსტი (RU)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_secondary_text_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='ღილაკი 2 ტექსტი (EN)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='cta_secondary_text_ru',
            field=models.CharField(blank=True, max_length=100, verbose_name='ღილაკი 2 ტექსტი (RU)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_primary_text',
            field=models.CharField(default='დაგვიკავშირდით', max_length=100, verbose_name='ღილაკი 1 ტექსტი (KA)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='cta_secondary_text',
            field=models.CharField(default='გაიგე მეტი', max_length=100, verbose_name='ღილაკი 2 ტექსტი (KA)'),
        ),
    ]
