# Generated by Django 5.2.4 on 2026-06-07 17:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_herosection_cta_primary_text_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='სათაური (ქა)')),
                ('title_en', models.CharField(blank=True, max_length=200, verbose_name='სათაური (EN)')),
                ('title_ru', models.CharField(blank=True, max_length=200, verbose_name='სათაური (RU)')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(default='Brain', help_text='lucide-react ხატულის სახელი, მაგ: Brain, Shield, Stethoscope', max_length=50, verbose_name='ხატულა (lucide icon name)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advantages/', verbose_name='სურათი')),
                ('video', models.FileField(blank=True, help_text='MP4 ფაილი. თუ ვიდეო ატვირთულია, სურათი არ გამოჩნდება.', null=True, upload_to='advantages/videos/', verbose_name='ვიდეო')),
                ('short_description', models.CharField(max_length=300, verbose_name='მოკლე აღწერა (ქა)')),
                ('short_description_en', models.CharField(blank=True, max_length=300, verbose_name='მოკლე აღწერა (EN)')),
                ('short_description_ru', models.CharField(blank=True, max_length=300, verbose_name='მოკლე აღწერა (RU)')),
                ('full_description', ckeditor.fields.RichTextField(blank=True, verbose_name='სრული აღწერა (ქა)')),
                ('full_description_en', ckeditor.fields.RichTextField(blank=True, verbose_name='სრული აღწერა (EN)')),
                ('full_description_ru', ckeditor.fields.RichTextField(blank=True, verbose_name='სრული აღწერა (RU)')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='თანმიმდევრობა')),
            ],
            options={
                'verbose_name': 'უპირატესობა',
                'verbose_name_plural': 'უპირატესობები (What is Mushroom)',
                'ordering': ['order'],
            },
        ),
    ]
