# Generated by Django 5.2.4 on 2026-05-28 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='სახელი')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='ხატულა')),
            ],
            options={
                'verbose_name': 'კატეგორია',
                'verbose_name_plural': 'კატეგორიები',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='სახელი')),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='აღწერა')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ფასი')),
                ('sale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='სარეალიზაციო ფასი')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='სურათი')),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='შეფასება')),
                ('stock_count', models.PositiveIntegerField(default=0, verbose_name='მარაგი')),
                ('is_active', models.BooleanField(default=True, verbose_name='აქტიური')),
                ('is_featured', models.BooleanField(default=False, verbose_name='გამოსახული')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='შექმნის თარიღი')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.productcategory', verbose_name='კატეგორია')),
            ],
            options={
                'verbose_name': 'პროდუქტი',
                'verbose_name_plural': 'პროდუქტები',
                'ordering': ['-created_at'],
            },
        ),
    ]
